# Generated by Django 5.1.7 on 2025-03-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_basketproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketproduct',
            name='quantity',
        ),
    ]
