# Generated by Django 5.1.7 on 2025-03-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_basketproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Количество'),
        ),
    ]
